name: moonbit-ci

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MoonBit
        uses: hustcer/setup-moonbit@v1

      - name: Install dependencies
        run: |
          moon update
          moon check --deny-warn

      - name: Check code (deny warnings)
        run: moon check --deny-warn

      - name: Run tests
        run: moon test --target native

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ZSeanYves/SimplexNoise
